name: Docker镜像构建推送

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 登录Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 构建Docker镜像
        run: docker build . --file Dockerfile --tag kpxyyyy/dnsmgr:latest

      - name: 推送到Docker Hub
        run: docker push kpxyyyy/dnsmgr:latest
